# Generated by Django 4.2.9 on 2024-07-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
