# Generated by Django 4.2.9 on 2024-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_menu_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
