# Generated by Django 5.1 on 2024-08-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0005_mesa_disponible"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_PROCESO", "En Proceso"),
                    ("COMPLETADA", "Completada"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="mesa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="administracion.mesa",
            ),
            preserve_default=False,
        ),
    ]
