# Generated by Django 5.1 on 2024-08-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0006_venta_estado_venta_mesa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="mesa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administracion.mesa",
            ),
        ),
    ]
