# Generated by Django 5.1 on 2024-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0008_alter_venta_mesa"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesa",
            name="reservada",
            field=models.BooleanField(default=False),
        ),
    ]
