# Generated by Django 5.1 on 2024-08-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0009_mesa_reservada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="menu_images/default.jpg",
                null=True,
                upload_to="menu_images/",
            ),
        ),
    ]
