# Generated by Django 5.1 on 2024-08-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0010_alter_menu_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="pagado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="puesto",
            field=models.CharField(
                choices=[
                    ("camarero", "Camarero"),
                    ("cocinero", "Cocinero"),
                    ("limpieza", "Limpieza"),
                    ("mantenimiento", "Mantenimiento"),
                ],
                max_length=100,
            ),
        ),
    ]
