# Generated by Django 5.1 on 2024-08-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_menu_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('camarero', 'Camarero'), ('cocinero', 'Cocinero'), ('limpieza', 'Limpieza'), ('mantenimiento', 'Mantenimiento')], max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO', 'Entregado'), ('PENDIENTE DE PAGO', 'Pendiente de Pago'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
    ]
