# Generated by Django 5.0.7 on 2024-08-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_menu_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('camarero', 'Camarero'), ('cocinero', 'Cocinero'), ('limpieza', 'Limpieza'), ('mantenimiento', 'Mantenimiento')], max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO', 'Entregado'), ('PENDIENTE_DE_PAGO', 'Pendiente de Pago'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
    ]
