# Generated by Django 5.0.7 on 2024-08-24 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_venta_precio_alter_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='transaccion_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO', 'Entregado'), ('PENDIENTE_DE_PAGO', 'Pendiente de Pago'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
    ]
